version: '3'

services:
  sportsfun-server:
    build: .
    container_name: sportsfun-server
    external_links:
      - mongodb:mdb
    ports:
      - 8080:8080
    volumes:
      - ./public:/opt/public
    networks:
      - mongodb
      - sportsfun

networks:
  mongodb:
    external:
      name: mongodb
  sportsfun:
    external:
      name: sportsfun