version: '3'

services:
  mongodb:
    image: mongo
    container_name: mdb
    restart: always
    volumes:
      - db:/data/db
    networks:
      - mongodb
  sportsfun-server:
    build: .
    container_name: sportsfun-server
    external_links:
      - mongodb:mdb
    ports:
      - 8080:8080
    volumes:
      - ./public:/opt/public
    networks:
      - mongodb

volumes:
  db:

networks:
  mongodb:
    external:
      name: mongodb
